name: Deploy to Droplet

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_DEV }}" > .env

      - name: Set up SSH
        run: |
          echo "${{ secrets.SSH_KEY_DEV }}" > ssh_key
          chmod 600 ssh_key

      - name: Copy files to Droplet
        run: |
          scp -i ssh_key -o StrictHostKeyChecking=no .env docker-compose.yml Dockerfile root@${{ secrets.REMOTE_HOST_DEV }}:/root/eliza/

      - name: Deploy to Droplet
        run: |
          ssh -i ssh_key -o StrictHostKeyChecking=no root@${{ secrets.REMOTE_HOST_DEV }} '
            cd /root/eliza
            docker compose down
            docker compose build --no-cache
            docker compose up -d
          '
