name: Deploy to Droplet

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_DEV }}" > .env

      - name: Set up SSH
        run: |
          echo "${{ secrets.SSH_KEY_DEV }}" > ssh_key
          chmod 600 ssh_key

      - name: Copy project files
        run: |
          # Create project directory on Droplet
          ssh -i ssh_key -o StrictHostKeyChecking=no root@${{ secrets.REMOTE_HOST_KEY }} 'mkdir -p /root/eliza'
          
          # Copy project files
          scp -i ssh_key -o StrictHostKeyChecking=no -r \
            src/ \
            public/ \
            package.json \
            .env \
            docker-compose.yml \
            Dockerfile \
            root@${{ secrets.REMOTE_HOST_KEY }}:/root/eliza/

      - name: Deploy with Docker Compose
        run: |
          ssh -i ssh_key -o StrictHostKeyChecking=no root@${{ secrets.REMOTE_HOST_KEY }} '
            cd /root/eliza
            docker compose down
            docker compose build --no-cache
            docker compose up -d
          '

      - name: Cleanup
        if: always()

        run: rm -f ssh_key











