name: Deploy to Droplet

on:
  push:
    branches: master

jobs:
  deploy:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_DEV }}" > .env

      - name: Set up SSH
        run: |
          echo "${{ secrets.SSH_KEY_DEV }}" > ssh_key
          chmod 600 ssh_key

      - name: Copy project files
        run: |
          # Create project directory on Droplet
          ssh -i ssh_key -o StrictHostKeyChecking=no root@${{ secrets.REMOTE_HOST_KEY }} 'mkdir -p /root/eliza'
          
          # Copy project files
          scp -i ssh_key -o StrictHostKeyChecking=no -r \
            src/ \
            public/ \
            package.json \
            .env \
            docker-compose.yml \
            Dockerfile \
            root@${{ secrets.REMOTE_HOST_KEY }}:/root/eliza/

      - name: Deploy with Docker Compose
        run: |
          ssh -i ssh_key -o StrictHostKeyChecking=no root@${{ secrets.REMOTE_HOST_KEY }} '
            cd /root/eliza
            docker compose down
            docker compose build --no-cache
            docker compose up -d
          '

      - name: Cleanup
        if: always()

        run: rm -f ssh_key

      # --- Discord Notification Step ---
      - name: Send Discord Notification on Failure
        if: failure() # This ensures the step only runs if any previous step in this job failed
        uses: Ilshidur/action-discord@master # Changed to Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL_ACTIONS }} # Pass the full webhook URL as an environment variable
        with:
          # The 'args' input is used to pass the message content to this action
          args: |
            🚨 **Deployment to EC2 Failed!** 🚨
            **Repository:** `${{ github.repository }}`
            **Workflow:** `${{ github.workflow }}`
            **Branch:** `${{ github.ref_name }}`
            **Commit:** `${{ github.sha }}`
            **Triggered by:** `${{ github.actor }}`
            **Run URL:** `${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}`
            Please investigate immediately! <@1015923238674640896>
          # Ilshidur/action-discord@master does not directly support 'username' or 'avatar_url' as inputs.
          # These would typically be configured directly in the Discord webhook settings,
          # or by sending a JSON payload with these fields if using a custom script.
          # For now, we'll remove them as they cause the 'Unexpected input(s)' warning.

















